import { describe, expect, it } from "vitest";

import { applyExcludes } from "./excludes.js";
import type { ParsedFile } from "./types.js";

const file = (path: string): ParsedFile => ({
  path,
  status: "modified",
  additions: 1,
  deletions: 0,
  is_binary: false,
  hunks: [],
});

describe("applyExcludes (default rules)", () => {
  it("drops lock files with reason", () => {
    const r = applyExcludes([file("src/foo.ts"), file("package-lock.json")]);
    expect(r.kept.map((f) => f.path)).toEqual(["src/foo.ts"]);
    expect(r.excluded).toEqual([
      { path: "package-lock.json", reason: "lock file" },
    ]);
  });

  it("drops build output", () => {
    const r = applyExcludes([
      file("src/foo.ts"),
      file("dist/index.js"),
      file("build/bundle.css"),
    ]);
    expect(r.kept.map((f) => f.path)).toEqual(["src/foo.ts"]);
    expect(r.excluded.map((e) => e.path)).toEqual([
      "dist/index.js",
      "build/bundle.css",
    ]);
  });

  it("drops vendored deps", () => {
    const r = applyExcludes([file("vendor/foo.go"), file("node_modules/x/index.js")]);
    expect(r.kept).toEqual([]);
    expect(r.excluded).toHaveLength(2);
  });

  it("drops generated proto", () => {
    const r = applyExcludes([
      file("svc/api.pb.go"),
      file("api/v1/types_pb2.py"),
      file("api/v1/types_pb2_grpc.py"),
    ]);
    expect(r.kept).toEqual([]);
  });

  it("drops snapshots", () => {
    const r = applyExcludes([file("__snapshots__/x.test.ts.snap")]);
    expect(r.kept).toEqual([]);
    expect(r.excluded[0].reason).toBe("test snapshot");
  });
});

describe("applyExcludes (includeGenerated bypass)", () => {
  it("keeps everything when includeGenerated=true", () => {
    const r = applyExcludes(
      [file("package-lock.json"), file("dist/index.js")],
      { includeGenerated: true },
    );
    expect(r.kept).toHaveLength(2);
    expect(r.excluded).toEqual([]);
  });
});

describe("applyExcludes (caller includes)", () => {
  it("applies allowlist before defaults", () => {
    const r = applyExcludes(
      [file("src/a.ts"), file("docs/b.md"), file("test/c.spec.ts")],
      { includes: ["src/**"] },
    );
    expect(r.kept.map((f) => f.path)).toEqual(["src/a.ts"]);
    expect(r.excluded.map((e) => e.reason)).toContain("not in includes filter");
  });
});

describe("applyExcludes (caller extra excludes)", () => {
  it("layers on top of defaults", () => {
    // Use a path that doesn't match any default rule so we know the
    // caller pattern is what dropped it.
    const r = applyExcludes(
      [file("src/a.ts"), file("src/b.fixture.ts")],
      { extraExcludes: ["**/*.fixture.ts"] },
    );
    expect(r.kept.map((f) => f.path)).toEqual(["src/a.ts"]);
    expect(r.excluded[0].path).toBe("src/b.fixture.ts");
    expect(r.excluded[0].reason).toContain("excluded by caller pattern");
  });
});
